#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local url_server_Linux="https://dl.k8s.io/v${KUBERNETES_VERSION}/kubernetes-server-linux-amd64.tar.gz"

  case "$(uname -s)" in
    Linux)
      sudo aptitude install -y ebtables ethtool socat

      local url_server="url_server_$(uname -s)"
      local fnm_server="$(basename "${!url_server}")"
      cache curl "$fnm_server" "${!url_server}"

      mkdir -p "$shome/vendor/k8s-${KUBERNETES_VERSION}"
      pushd "$shome/vendor/k8s-${KUBERNETES_VERSION}"
      tar xvfz "${BASEBOX_CACHE}/curl/$fnm_server"
      popd
      ;;
  esac
}

main "$@"
