#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  case "$(uname -s)" in
    Linux)
      true
      ;;
    *)
      return 1
      ;;
  esac

  if [[ "$($shome/script/version | jq -r '.k8s')" != "$KUBERNETES_VERSION" ]]; then
    return 1
  fi

  return 0
}

source sub "$BASH_SOURCE" "$@"
