#!/usr/bin/env bash

function version {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"
  source "$shome/script/profile"

  local ver_k8s="$(kubelet --version 2>/dev/null | awk '{print $2}' | perl -pe 's{^v}{}' || true)"
  jq -n --arg k8s "$ver_k8s" '{k8s: $k8s}'
}

version "$@"
